import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import CartEvent from "@/components/ui/CartEvent";
import Cart from "@/components/modals/Cart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth" data-mode="light" dir="ltr">
      <head>
        <meta charSet="utf-8" />
        <title>Shajgoj - Buy authentic cosmetic and beauty products online in Bangladesh</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta content="Shajgoj" name="Shajgoj is the first online cosmetic and beauty products store in Bangladesh" />
        <meta content="Shajgoj" name="random author" />
      </head>
       <body className="text-base font-body">
        <Header />
        <CartEvent />
        {/* <Cart /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
